### ISSUE TITLE
Modelling prismatic joints fails if more than 1 joint is modeled

### ISSUE THREAD

**Issue by kristsaet** [openfedem/fedem-gui#24]
The second prismatic joint modeled get the same master-segment curve as the first prismatic.
And joint is corrupt. Has to be manually handled by editing the FMM file, and adding the second master-line manually.

**Comment by kmokstad** [comment]
This I was not able to reproduce on a random model (see image below). I tried to create two prismatic joints on a simple shell part and they both looks OK to me. Or do you mean placing two prismatics on the same location (only with the slave triad a different place)? In that case it is intended the two prismatics will share the same glider when they both are attached to the FE part.

![{F7557385-9BB2-4563-B8C2-C3D953C2AD17}](https://github.com/user-attachments/assets/8c19b909-24e2-4840-a496-e32ba7c0e1e8)

@kristsaet You need to describe this issue more accurately before it can be addressed further.
