### ISSUE TITLE
Save As not adding .fmm file extension as standard anymore?

### ISSUE THREAD

**Issue by kristsaet** [openfedem/fedem-gui#27]
As pr. title, when saving a file, and the type of .fmm is selected, the extension is not added to the filename unless you explicitly ends the filename with .fmm in the File name field.

![image](https://github.com/user-attachments/assets/6fa3d3b4-4594-48c1-af84-92fb0bdc9967)

**Comment by kmokstad** [comment]
Actually, I don't think we ever did add the `.fmm` extension in this case. At not least since R7.3. But I agree it makes sense to do it as this would be the expected behavior for most users. Easily added.
