### ISSUE TITLE
Copying data into polyline function is corrupt

### ISSUE THREAD

**Issue by kristsaet** [openfedem/fedem-gui#39]
Trying to copy this data ctrl+c --> ctrl+v into a Polyline function in the Fedem GUI

#Description,y
5.0,-0.0
5.01002004008016,-4.012009535614797e-07
5.020040080160321,-3.199953714739321e-06
5.030060120240481,-1.0767314189855441e-05
5.040080160320641,-2.5445539446494664e-05
5.050100200400801,-4.9548204072454885e-05
5.060120240480962,-8.5360316534684e-05
5.070140280561122,-0.00013513843553822862
5.080160320641283,-0.00020111078638517747
5.090180360721443,-0.0002854773773336057
5.1002004008016035,-0.00039041011595651967

The data that occur in the UI is as shown:
It looks like only the time values are used as both x and y values.

![{E04E23F5-DBDE-4F95-9D2A-398E3FA05356}](https://github.com/user-attachments/assets/153bb809-b953-4c3e-b18e-744fe1e6d57b)

**Comment by kmokstad** [comment]
Yes, there seems to be a problem with comma-separated data in the copy-paste feature. If you replace the commas with space, the data comes in correctly.
